title: About me
logo: hi.png
description: Computational Mathematics & Data Science Lab, Department of Mathematics, IIT Madras, India
github: false
favicon: "abdul profile photo.jpg"
# show_downloads: true
theme: jekyll-theme-minimal

