title: About me
logo: hi.png
description: Computational Mathematics & Data Science Lab, Department of Mathematics,Indian Institute of technology,IIT Madras,Chennai,Tamil Nadu,India- 600 036

# show_downloads: true
theme: jekyll-theme-minimal
social:
  github: yourusername
  twitter: yourusername
  linkedin: yourusername

