title: About me
logo: hi.png
description: Computational Mathematics & Data Science Lab, Department of Mathematics,Indian Institute of technology,IIT Madras,Chennai,Tamil Nadu,India- 600 036

# show_downloads: true
theme: jekyll-theme-minimal

# URL settings
baseurl: "https://yourusername.github.io" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
