title: About me
logo: NEW.png
description: Computational Mathematics & Data Science Lab, Department of Mathematics, IIT Madras, India
github: false
# show_downloads: true
theme: jekyll-theme-minimal

